# example spline interpolation 
commercial <- read.csv("commercial energy.csv")
all.years <- 1992:2040
heat <- splinefun(commercial$Year, commercial$Space.Heating)
cool <- splinefun(commercial$Year, commercial$Space.Cooling)
water <- splinefun(commercial$Year, commercial$Water.Heating)
ventilation <- splinefun(commercial$Year, commercial$Ventilation)
cooking <- splinefun(commercial$Year, commercial$Cooking)
lighting <- splinefun(commercial$Year, commercial$Lighting)
refrigeration <- splinefun(commercial$Year, commercial$Refrigeration)
office.equip <- splinefun(commercial$Year, commercial$Office.Equipment)
other <- splinefun(commercial$Year, commercial$Other)
Year <- all.years
Space.Heating <- heat(all.years)
Space.Cooling <- cool(all.years)
Water.Heating <- water(all.years)
Ventilation <- ventilation(all.years)
Cooking <- cooking(all.years)
Lighting <- lighting(all.years)
Refrigeration <- refrigeration(all.years)
Office.Equipment <- office.equip(all.years)
Other <- other(all.years)
commercial.energy <- data.frame(Year, Space.Heating, Space.Cooling, Water.Heating, Ventilation, Cooking, Lighting, Refrigeration, Office.Equipment, Other)
write.csv(commercial.energy, file="commercial.energy.csv")